# production envrionment configuration file
spring:
#  jpa.hibernate.ddl-auto: validate
#  h2.console:
#    enabled: true
#    path: /h2-console
#  devtools:
#    restart.enabled: false
#  datasource:
#    schema:
#    data: 
#    url: jdbc:h2:./data/h2/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: test
#    password: test
#    max-active: 10

logging.file: D:\tmp\spring-boot.log